# Generated by Django 4.0.3 on 2022-04-08 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, default='uploads/default.jpg', max_length=2000, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
