# Generated by Django 4.0.3 on 2022-04-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0002_item_img_item_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
    ]
