# Generated by Django 4.0.3 on 2022-04-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0003_remove_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, default='uploads/default.jpg', max_length=2000, upload_to='uploads/'),
        ),
    ]
