# Generated by Django 4.0.3 on 2022-04-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0004_item_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
    ]
