# Generated by Django 4.0.3 on 2022-04-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0012_remove_item_img_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
